title: "Klárčin blog"
# description: "~~Mistr a Markétka~~ Medvěd a Klárka"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://matcha1309.github.io"

logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%-d. %B, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
skin: "/assets/css/skins/default.css"
locale: cs-CZ

navigation:
  - title: Home
    url: /
  - title: O mně
    url: /about/
  - title: Galerie
    url: /galerie/
  - title: RSS/Atom
    url: /feed.xml

# Site Author
author:
  name: Klárka
  picture: assets/img/klarka-pfp.jpg
  email:
  links:
    - title:
      url:
      icon:

#######################################################################################

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: feed.xml


collections:
  comics:
    output: true
    permalink: /comics/:title/




# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "comics"
    values:
      layout: "comics-page"


# Liquid
liquid:
  error_mode: strict


plugins:
  - jektex


exclude:
   - .sass-cache/
   - .jekyll-cache/
   - .jektex-cache
   - .vendor/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - LICENSE
   - README.md
   - makefile

